
services:
  social-auto-upload:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-auto-upload:latest
    container_name: social-auto-upload
    restart: unless-stopped
    ports:
      - "5409:5409"
    volumes:
      - downloads:/app/downloads
      - ./douyin_credentials.json:/app/douyin_credentials.json
      - ./db:/app/db
    environment:
      VIDEO_DOWNLOAD_PATH: /app/downloads
      DOUYIN_CREDENTIALS_FILE: /app/douyin_credentials.json
      TZ: Asia/Shanghai
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      no_proxy: asr,nlp,gateway,localhost,127.0.0.1

    # 等价于 -it
    tty: true
    stdin_open: true

volumes:
  downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/c/workspaces/yt/downloads

